version: '3.9'
services:
  app:
    container_name: homelibservice-app
    build: .
    image: kopfmann/homelibservice-auth-app
    restart: always
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - postgres
    volumes:
      - ./src:/app/src
    env_file:
      - .env
    networks:
      - ${NETWORK}

  postgres:
    container_name: homelibservice-db
    build: ./src/database
    image: kopfmann/homelibservice-auth-db
    restart: always
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    env_file:
      - .env
    volumes:
      - /var/lib/postgresql/data
    command:
      [
        'postgres',
        '-c',
        'logging_collector=on',
        '-c',
        'log_directory=./',
        '-c',
        'log_filename=postgres.log',
        '-c',
        'log_statement=all',
      ]

    networks:
      - ${NETWORK}

networks:
  library-service:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: '192.168.0.0/24'
          gateway: '192.168.0.1'
    name: ${NETWORK}

volumes:
  app:
  postgres:
