version: '3.9'
services:
  app:
    container_name: nodejs-app
    image: kopfmann/homelibservice-app
    restart: always
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - postgres
    volumes:
      - ./src:/app/src
    environment:
      DATABASE_URL: ${DATABASE_URL}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_HOST: ${POSTGRES_DB}
    networks:
      - ${NETWORK}

  postgres:
    container_name: postgres-db
    image: kopfmann/homelibservice-db 
    restart: always
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST_AUTH_METHOD: trust
      PGDATA: /var/lib/postgresql/data
    volumes:
      - /var/lib/postgresql/data
    networks:
      - ${NETWORK}

networks:
  library-service:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: '192.168.0.0/24'
          gateway: '192.168.0.1'
    name: ${NETWORK}

volumes:
  app:
  postgres:
